FROM python:alpine

LABEL org.opencontainers.image.description=abcdesktop.pyos

## install kerberos libgss ldap
## we must install curl command line for pullapps bash script 

RUN apk upgrade --no-cache && \
    apk update --no-cache  && \
    apk add --no-cache \
 	wget \
	curl \
	cntlm \
	krb5 \
	krb5-libs \
	libgsasl \
	samba-winbind-clients
# gss-ntlmssp krb5-user krb5-config sasl2-bin


ENV GEOLITE_URL=https://github.com/P3TERX/GeoLite.mmdb/raw/download

# GeoLite2
RUN mkdir -p /usr/share/geolite2 && \
    wget ${GEOLITE_URL}/GeoLite2-ASN.mmdb -P /usr/share/geolite2 && \
    wget ${GEOLITE_URL}/GeoLite2-City.mmdb -P /usr/share/geolite2

# install ntlm_auth
# ghcr.io/abcdesktopio/ntlm_auth:debian_bookworm is multi-arch 
# support for linux_arm64 and linux_amd64
# FROM python is a debian:bookworm image

RUN apk add --no-cache \
	krb5-dev \
	gcc \
	musl-dev \
	py3-ldap \
	py3-ldap-pyc \
    py3-python-gssapi-pyc \
    samba-libs \
    py3-python-gssapi \
    krb5-dev \
	geoip-dev \
	openldap-dev

RUN mkdir /dist
# COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /aports/main/samba/src/samba-*/bin/ntlm_auth /var/pyos/oc/auth/ntlm/ntlm_auth
COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /dist/bin/ntlm_auth /var/pyos/oc/auth/ntlm/ntlm_auth
# COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /dist/lib /usr/lib
# /root/packages/main/x86_64 or /root/packages/main/arm_64
COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /root/packages/main/*/ /dist
COPY --from=ghcr.io/abcdesktopio/root/.abuild/*.pub /etc/apk/keys
RUN ls -la /dist && apk add /dist/*.apk


# install pyos in /var/pyos
WORKDIR /var/pyos
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# remove dev package
# should better use a builder instance
# but I can't find how to grab all new libraries
RUN apk del --no-cache \
	krb5-dev \
        gcc \
        musl-dev \
        krb5-dev \
        geoip-dev \
        openldap-dev

# create log directory
RUN mkdir -p /var/pyos/logs
# CMD is od.py
CMD [ "./od.py" ]
