FROM python:alpine

LABEL org.opencontainers.image.description=abcdesktop.pyos

## install kerberos libgss ldap
## we must install curl command line for pullapps bash script 

RUN apk update --no-cache && \
    apk upgrade --no-cache && \
    apk add --no-cache --update \
 	wget \
	curl \
	cntlm \
	krb5 \
	krb5-libs \
	libgsasl \
	"libssl3>3.5.4" \
	"libcrypto3>3.5.4"

#   gss-ntlmssp 
#   krb5-user 
#   krb5-config sasl2-bin


ENV GEOLITE_URL=https://github.com/P3TERX/GeoLite.mmdb/raw/download

# GeoLite2
RUN mkdir -p /usr/share/geolite2 && \
    wget ${GEOLITE_URL}/GeoLite2-ASN.mmdb -P /usr/share/geolite2 && \
    wget ${GEOLITE_URL}/GeoLite2-City.mmdb -P /usr/share/geolite2

# install ntlm_auth
# ghcr.io/abcdesktopio/ntlm_auth:debian_bookworm is multi-arch 
# support for linux_arm64 and linux_amd64
# FROM python is a debian:bookworm image

RUN apk add --no-cache \
	krb5-dev \
	gcc \
	musl-dev \
	py3-ldap \
	py3-ldap-pyc \
    py3-python-gssapi-pyc \
    py3-python-gssapi \
    krb5-dev \
	geoip-dev \
	openldap-dev

##################
# Commented for alpine no install ntlm_auth / samba support 
# use ubuntu image to get SSO features
# - ghcr.io/abcdesktopio/ntlm_auth:debian_bookworm is multi-arch 
# - support for linux_arm64 and linux_amd64
# FROM python is a debian:bookworm image
# RUN mkdir /dist
# COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /dist/bin/ntlm_auth /var/pyos/oc/auth/ntlm/ntlm_auth
# COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /root/packages/main/*/ /dist
# COPY --from=ghcr.io/abcdesktopio/ntlm_auth:alpine_edge /root/.abuild/*.pub /etc/apk/keys
# RUN apk update  && apk add --no-cache /dist/*.apk
##################

# install pyos in /var/pyos
WORKDIR /var/pyos
COPY . .
# install upgrade pip
# install requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# remove dev package
# should better use a builder instance
# but I can't find how to grab all new libraries
RUN apk del --no-cache \
	krb5-dev \
    gcc \
    musl-dev \
    krb5-dev \
    geoip-dev \
    openldap-dev

# create log directory
RUN mkdir -p /var/pyos/logs
# CMD is od.py
CMD [ "./od.py" ]
